### ISSUE TITLE
Archivos Corruptos

### ISSUE THREAD

**Issue by benjavides** [IIC2613/Material-semestres-anteriores#1]
Hola, no puedo abrir ninguno de los archivos, están corruptos.
![image](https://user-images.githubusercontent.com/7333792/31293457-a36d3af0-aaad-11e7-97f7-3b80c55e0161.png)
No es un problema de Adobe Reader, con Chrome tampoco abren. Además dice que pesan alrededor de 130 bytes cada uno. Intenté clonando y descargando directamente desde la página de github.
No tengo instalado el LFS, es estrictamente necesario?

**Comment by aaossa** [comment]
Mmm revisaré lo de si es necesario. En cuanto a descargarlo, yo puedo verlo directamente en GitHub, y descargarlo desde GitHub y visualizarlo localmente, todo sin problemas. Si instalas Git LFS y el problema desaparece, cerramos la issue. 

PS: Podrías intentar descargando el repositorio como `.zip` y verificar si sigues con el mismo problema.

**Comment by benjavides** [comment]
Intenté clonando el repo, bajando el zip, mismo problema. Antes y después de instalar LFS.
Probé bajando el .zip desde otro navegador pensando que podría tener cacheado el archivo, tampoco funciona.
Finalmente lo logré clonando el repo desde la consola, antes estaba intentado hacerlo usando GitKraken (GUI para manejar GIT). Igual no entiendo por qué no funcionaba bajando el .zip

**Comment by aaossa** [comment]
El `.zip` no debería verse afectado si tienes Git LFS o no, así que eso era esperable. Leyendo sobre [GitKraken y archivos de LFS](https://support.gitkraken.com/git-lfs/working-with-files) parece que los archivos de ~130 bytes que veías (tanto con Git sin LFS como descargando el `.zip`) son las referencias de Git LFS al archivo:

> ![Referencia a un archivo de Git LFS](https://support.gitkraken.com/img/documentation/git-lfs/lfs-ref@2x.png)
> 
> Imagen tomada del artículo de GitKraken.

Seguramente la relación entre GitKraken y Git LFS aún tiene sus defectos porque Git LFS es un poco reciente, pero en el futuro supongo que deberán trabajar mejor. Además, creo que el éxito de GitKraken con estos repos también depende de si tienes Git LFS.  Gracias por el aviso 🙌
